module.exports = [
    {
        title: '2ality feed',
        url: 'http://feeds.feedburner.com/2ality'
    }, {
        title: 'bitsofcode',
        url: 'https://bitsofco.de/rss/'
    }, {
        title: 'C-Tone',
        url: 'https://creamidea.github.io/static/rss2.xml'
    }, {
        title: 'Damonare',
        url: 'http://blog.damonare.cn/atom.xml'
    }, {
        title: 'DaraW',
        url: 'http://blog.daraw.cn/atom.xml'
    }, {
        title: 'ELSE携程技术周刊',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/itech',
        link: 'https://zhuanlan.zhihu.com/itech'
    }, {
        title: '饿了么前端',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/ElemeFE',
        link: 'https://zhuanlan.zhihu.com/ElemeFE'
    }, {
        title: '某熊的全栈之路',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/wxyyxc1992',
        link: 'https://zhuanlan.zhihu.com/wxyyxc1992'
    }, {
        title: '前端杂货铺',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/jscss',
        link: 'https://zhuanlan.zhihu.com/ElemeFE'
    }, {
        title: '腾讯Stark伟',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/starkwang',
        link: 'https://zhuanlan.zhihu.com/starkwang'
    }, {
        title: '前端外刊评论',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/FrontendMagazine',
        link: 'https://zhuanlan.zhihu.com/FrontendMagazine'
    }, {
        title: '大搜车染陌',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/ranmo',
        link: 'https://zhuanlan.zhihu.com/ranmo'
    }, {
        title: '阿里云前端dawn团队专栏',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/aliyun',
        link: 'https://zhuanlan.zhihu.com/aliyun'
    }, {
        title: '美团点评点餐事业部终端团队',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/mtdpdiancan',
        link: 'https://zhuanlan.zhihu.com/mtdpdiancan'
    }, {
        title: '颜海镜',
        url: 'https://rss.lilydjwg.me/zhihuzhuanlan/yanhaijing',
        link: 'https://zhuanlan.zhihu.com/yanhaijing'
    }, {
        title: 'Harttle Land',
        url: 'http://harttle.com/feed.xml'
    }, {
        title: 'I code it',
        url: 'http://icodeit.org/atom.xml'
    }, {
        title: 'iHardCoder搜狗前端',
        url: 'http://feed.cnblogs.com/blog/u/173153/rss'
    }, {
        title: 'chunfenglee',
        url: 'http://chunfenglee.com/atom.xml'
    }, {
        title: 'JavaScript Weekly',
        url: 'http://javascriptweekly.com/rss/11m9nlg9'
    }, {
        title: 'JerryQu',
        url: 'https://imququ.com/rss.html'
    }, {
        title: "Jim Liu's Blog",
        url: 'http://manjusaka.itscoder.com/atom.xml'
    }, {
        title: 'Node Weekly',
        url: 'https://nodeweekly.com/rss/11kgdl44'
    }, {
        title: 'nodejh',
        url: 'http://nodejh.com/index.xml'
    }, {
        title: 'Taobao FED',
        url: 'http://taobaofed.org/atom.xml'
    }, {
        title: 'the5fire',
        url: 'https://www.the5fire.com/rss/'
    }, {
        title: 'Web技术研究所',
        url: 'https://www.web-tinker.com/rss.xml'
    }, {
        title: 'xcatliu',
        url: 'http://blog.xcatliu.com/atom.xml'
    }, {
        title: '人人网FED',
        url: 'https://fed.renren.com/feed/'
    }, {
        title: '十年踪迹的博客',
        url: 'https://www.h5jun.com/rss.html'
    }, {
        title: 'Darren_聂微东',
        url: 'http://feed.cnblogs.com/blog/u/79919/rss'
    }, {
        title: '韩子迟',
        url: 'http://feed.cnblogs.com/blog/u/199121/rss'
    }, {
        title: '叶小钗',
        url: 'http://feed.cnblogs.com/blog/u/91319/rss'
    }, {
        title: '纪沧海',
        url: 'http://feed.cnblogs.com/blog/u/223719/rss'
    }, {
        title: '龙恩0707',
        url: 'http://feed.cnblogs.com/blog/u/161525/rss'
    }, {
        title: '咀嚼之味',
        url: 'http://jerryzou.com/feed.xml'
    }, {
        title: '奇舞周刊',
        url: 'https://weekly.75team.com/rss.php'
    }, {
        title: '小胡子哥',
        url: 'http://barretlee.com/rss2.xml'
    }, {
        title: '掘金前端',
        url: 'https://api.prprpr.me/xitu/frontend'
    }, {
        title: '文蔺',
        url: 'http://www.wemlion.com/atom.xml'
    }, {
        title: '水能载舟 亦可赛艇',
        url: 'https://lengzzz.com/rss'
    }, {
        title: '熊建刚的博客',
        url: 'http://blog.codingplayboy.com/feed/'
    }, {
        title: '王子亭',
        url: 'https://jysperm.me/atom.xml'
    }, {
        title: '腾讯_ChokCoco_CSS',
        url: 'http://feed.cnblogs.com/blog/u/177636/rss'
    }, {
        title: '酷 壳 – CoolShell',
        url: 'http://coolshell.cn/feed'
    }, {
        title: '阮一峰',
        url: 'http://www.ruanyifeng.com/blog/atom.xml'
    }
]
